import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/components/Header";

import Head from "next/head";

import Script from "next/script";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		/* 客户端会多一个 class="dark" 导致不一致 */
		<html lang="en" suppressHydrationWarning={true}>
			<head>
				<script
					dangerouslySetInnerHTML={{
						__html: `
					(function() {
						const theme = localStorage.getItem('theme') || 'dark';
						document.documentElement.classList.add(theme==='dark' ? 'dark' : '');
      		        })();`,
					}}
				></script>
			</head>
			<body className="bg-gray-50 text-gray-900">
				<Header />
				{children}
			</body>
		</html>
	);
}
